### ISSUE TITLE
explode(): Argument #2 ($string) must be of type string, bool given

### ISSUE THREAD

**Issue by stprasst** [adityadees/laravel-bard#3]
Hi @adityadees 
I tried using this package, the results shown are quite good.
but sometimes an error like this appears:
explode(): Argument #2 ($string) must be of type string, bool given
in this line:  $bard = (new LaravelBard())->get_answer('what is linux');
when testing do get_answer several times

thanks

**Comment by adityadees** [comment]
hi @stprasst  this because timeout issue
Try to increase the timeout 
``` php
$yourTImeout = 30; // seconds
$bard = (new LaravelBard($yourTImeout))->get_answer('what is linux');
````

**Comment by adityadees** [comment]
@stprasst 
I've set default timeout to 60 seconds #4 
I'll mark this issue as resolved, you can repopen or create new issue if still have any problems.
thanks
